# https://docs.cocogitto.io/reference/config.html

tag_prefix = "v"
from_latest_tag = true
branch_whitelist = ["main", "master"]
ignore_merge_commits = true
ignore_fixup_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
pre = "beta.*"
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    # "cargo build --release",
    "echo 'bumping from {{latest|v0.0.0}} to {{version|v0.0.1}}'",
]
post_bump_hooks = ["git push", "git push origin {{version_tag}}"]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[changelog]
path = "CHANGELOG.md"
template = "default"
authors = []

[bump_profiles]

[git_hooks]
# 支持在 commit-msg 阶段自动校验 Conventional Commits
commit-msg = "cog check --hook"

[commit_types]
