# mise global config
[tool_alias]
sbox = "github:sagernet/sing-box"
gater = "github:cao7113/gater"
gater-client = "github:cao7113/gater"

[tools]
usage = "latest"
bun = "1.3.14"
erlang = "29.0.3"
elixir = "1.20.2-otp-29"
go = "1.26.6"
gater = "latest"
mkcert = "latest"

[tools.sbox]
version = "1.14.0-beta.14"
prerelease = "true"

[tools.gater-client]
version = "latest"
matching = "gater-client"

[settings]
experimental = true
status.show_env = true
minimum_release_age = "0"
# asdf_compat = true

[settings.github]
use_git_credentials = true
