# mise global config
[tool_alias]
sbox = "github:sagernet/sing-box"

[tools]
usage = "latest"

bun = "1.3.14"
erlang = "29.0.3"
elixir = "1.20.2-otp-29"
sbox = { version = "1.14.0-beta.14", prerelease = "true" }

[settings]
experimental = true
status.show_env = true
asdf_compat = true

[settings.github]
use_git_credentials = true
