# https://taskfile.dev/docs/guide
# https://taskfile.dev/reference/templating/
version: '3'
tasks:
  default: echo hi MacOS!

  setup.xcode: |
    xcode-select --install

  doc: |
    mkdir -p doc
    cd doc
    man arch | col -b > arch-man.txt
    man log | col -b > log-man.txt
    # launchctl help > launchctl-help.txt
    man launchctl | col -b > launchctl.txt

  # osascript -e "display notification \"$msg\" with title \"🔑 Keychain 访问失败\" subtitle \"Security Toolset\" sound name \"Basso\""
