# https://taskfile.dev
version: "3"

tasks:
  ## Fly Machines
  # try with tmp ubuntu
  try: fly machine run --shell

  # fly auth login
  # fly help

  ## Setup
  v: |
    fly version
    ls -l $(which fly)
  setup: |
    brew install flyctl
    fly version
  up: |
    brew upgrade flyctl
    fly version
    # fly version upgrade
