# https://taskfile.dev
version: "3"
# https://gist.github.com/ogrrd/5831371
tasks:
  help: /opt/homebrew/sbin/dnsmasq --help
  conf: |
    less /opt/homebrew/etc/dnsmasq.conf
    # /opt/homebrew/etc/dnsmasq.conf -7 /opt/homebrew/etc/dnsmasq.d,\*.conf
  log: |
    log show --predicate 'process == "dnsmasq"' --info
    # tail -f /opt/homebrew/var/log/dnsmasq.log

  restart: |
    sudo brew services restart dnsmasq
  start: |
    sudo brew services start dnsmasq
  stop: |
    sudo brew services stop dnsmasq
  setup: |
    brew install dnsmasq
