# /etc/dnsmasq.conf

# 监听本地地址
listen-address=127.0.0.1

# 基础域名地址映射 (A 记录)
address=/.l/127.0.0.1
address=/.h/127.0.0.1
address=/.s/127.0.0.1

# CNAME 配置：将 lv.s 指向 livebook.s
# dig @127.0.0.1 lv.s
# ping -c 1 lv.s
# 验证请求的Host 还是 lv.s /usr/bin/curl -v https://lv.s
# cname=lv.s,livebook.s